version: "3"

services:
  frontend:
    image: <image-name>
    ports:
      - "3000:3000"
  
  backend:
    image: <image-name>
    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - 6379:6379
  
  mongo:
    image: mongo
    ports:
      - 27017:27017